### ISSUE TITLE
Image Uploading

### ISSUE THREAD

**Issue by rserur** [LaunchAcademy/fauteuil#12]

**Comment by PatrickArthur** [comment]
I created two tests that are currently failing that check to see if an image is attached and when user submits, it shows a success message and one to test the show/index page to see if the photo is being uploaded. Running into some issues with carrierwave, I think it may have something to do with Rmajick . Currently, if a User fills out the form under chairs/new, it says it won't save. Also, I am using the Capybara attached_file and it says the column picture does not exist in the chairs model, need to figure out why we have that issue.
