### ISSUE TITLE
Edit Profile

### ISSUE THREAD

**Issue by rserur** [LaunchAcademy/fauteuil#2]
Edit Profile (non-core)

As a user I want to be able to edit my profile so I can update my information if I am not satisfied

Acceptance Criteria

The edit profile option is ONLY AVAIBALE WHEN A USER IS SIGNED IN
To Edit profile, I should be able to click on the "edit profile" button and be redirected to a page where I can see my current information and a form to edit that information
All fields (inclduing picture) should be editable.
If I succesfully edit my information, the page is re-rendered with updated info
I shoudl be able to go back to homepage

**Comment by PatrickArthur** [comment]
The edit profile is created along with the other parts of Devise, I have modified it to include the username and will need to add the ability to edit pictures. Need to add tests, have similar ones set up for New Profile, can get to that tomorrow.
